FROM pytorch/torchserve:0.11.0-cpu as builder

WORKDIR /app

COPY . ./

USER root

RUN chown -R 1000:1000 /app && chmod -R 775 /app

USER 1000

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

ENTRYPOINT python app.py
