FROM pytorch/torchserve:0.11.0-cpu as builder

WORKDIR /app

COPY . ./

RUN chown -R 1000:1000 /app

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

ENTRYPOINT python app.py
